- name: install and start nginx
  hosts: frontend
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: start nginc
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes