- name: install packages using loops
  hosts: localhost
  become: yes
  tasks:
  - name: install multiple packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
      - nginx
      - mysql
      - zip